# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2db40d28c2e7d5144d1c4db1cdc64f126949143226710cc268ec0ae7ae4923e825fd9479b6fdbc4c408eecb3a8dd7ba1b2a472e74f22f58d81657e37378503d

test:
  secret_key_base: 4393523c8eb1debede14d382003594e96747fe271d77bad51d91fc6f805523b334501c5b9df52b0f701f96f0d44d71ebe33ebf45909dd77e122e07a544d5c5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
